name: image_triangulation
channels:
  - nvidia
  - pytorch
  - conda-forge
  - fvcore
  - iopath
  - pytorch3d
dependencies:
  - python=3.10
  - cudatoolkit=11.7
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - opencv=4.7.0
  - numpy
  - matplotlib
  - pandas
  - tqdm
  - fvcore
  - iopath
  - pytorch3d::pytorch3d=0.7.3
  - scipy=1.10
  - matplotlib=3.7.1